var searchStrByHexFaInput = "", searchStrByFaHexInput = "";       
var hexFaIcon = document.getElementById("hexFaIcon"); 
var faHexIcon = document.getElementById("faHexIcon");
var iconFound = ""; 
var hexFound = ""; 

var escapeIndex = {
    "fontAwesomeIcons":[
         /* Accesibilidad */
         {"icon":"american-sign-language-interpreting","unicodeEscape":"f2a3"},
         {"icon":"asl-interpreting","unicodeEscape":"f2a3"},
         {"icon":"assistive-listening-systems","unicodeEscape":"f2a2"},
         {"icon":"audio-description","unicodeEscape":"f29e"},
         {"icon":"blind","unicodeEscape":"f29d"},
         {"icon":"braille","unicodeEscape":"f2a1"},
         {"icon":"cc","unicodeEscape":"f20a"},
         {"icon":"deaf", "unicodeEscape":"f2a4"},
         {"icon":"deafness","unicodeEscape":"f2a4"},
         {"icon":"hard-of-hearing", "unicodeEscape":"f2a4"},
         {"icon":"low-vision","unicodeEscape":"f2a8"},
         {"icon":"question-circle-o","unicodeEscape":"f29c"},
         {"icon":"sign-language","unicodeEscape":"f2a7"},
         {"icon":"signing", "unicodeEscape":"f2a7"},
         {"icon":"tty","unicodeEscape":"f1e4"},
         {"icon":"universal-access", "unicodeEscape":"f29a"},
         {"icon":"volume-control-phone", "unicodeEscape":"f2a0"},
         {"icon":"wheelchair", "unicodeEscape":"f193"},
         {"icon":"wheelchair-alt", "unicodeEscape":"f29b"},
         /* Mano */
         {"icon":"hand-grab-o","unicodeEscape":"f255"},
         {"icon":"hand-lizard-o","unicodeEscape":"f258"},
         {"icon":"hand-o-down","unicodeEscape":"f0a7"},
         {"icon":"hand-o-left","unicodeEscape":"f0a5"},
         {"icon":"hand-o-right","unicodeEscape":"f0a4"},
         {"icon":"hand-o-up","unicodeEscape":"f0a6"},
         {"icon":"hand-paper-o","unicodeEscape":"f256"},
         {"icon":"hand-peace-o","unicodeEscape":"f25b"},
         {"icon":"hand-pointer-o","unicodeEscape":"f25a"},
         {"icon":"hand-rock-o","unicodeEscape":"f255"},
         {"icon":"hand-scissors-o","unicodeEscape":"f257"},
         {"icon":"hand-spock-o","unicodeEscape":"f259"},
         {"icon":"hand-stop-o","unicodeEscape":"f256"},
         {"icon":"thumbs-down","unicodeEscape":"f165"},
         {"icon":"thumbs-o-down","unicodeEscape":"f088"},
         {"icon":"thumbs-o-up","unicodeEscape":"f087"},
         {"icon":"thumbs-up","unicodeEscape":"f164"},
         /* Transporte */
         {"icon":"ambulance","unicodeEscape":"f0f9"},
         {"icon":"automobile","unicodeEscape":"f1b9"},
         {"icon":"bicycle","unicodeEscape":"f206"},
         {"icon":"bus","unicodeEscape":"f207"},
         {"icon":"cab","unicodeEscape":"f1ba"},
         {"icon":"car","unicodeEscape":"f1b9"},
         {"icon":"fighter-jet","unicodeEscape":"f0fb"},
         {"icon":"motorcycle","unicodeEscape":"f21c"},
         {"icon":"plane","unicodeEscape":"f072"},
         {"icon":"rocket","unicodeEscape":"f135"},
         {"icon":"ship","unicodeEscape":"f21a"},
         {"icon":"space-shuttle","unicodeEscape":"f197"},
         {"icon":"subway","unicodeEscape":"f239"},
         {"icon":"taxi","unicodeEscape":"f1ba"},
         {"icon":"train","unicodeEscape":"f238"},
         {"icon":"truck","unicodeEscape":"f0d1"},
         {"icon":"wheelchair","unicodeEscape":"f193"},
         {"icon":"wheelchair-alt","unicodeEscape":"f29b"},
         /* Género */ 
         {"icon":"genderless","unicodeEscape":"f22d"},
         {"icon":"intersex","unicodeEscape":"f224"},
         {"icon":"mars","unicodeEscape":"f222"},
         {"icon":"mars-double","unicodeEscape":"f227"},
         {"icon":"mars-stroke","unicodeEscape":"f229"},
         {"icon":"mars-stroke-h","unicodeEscape":"f22b"},
         {"icon":"mars-stroke-v","unicodeEscape":"f22a"},
         {"icon":"mercury","unicodeEscape":"f223"},
         {"icon":"neuter","unicodeEscape":"f22c"},
         {"icon":"transgender","unicodeEscape":"f224"},
         {"icon":"transgender-alt","unicodeEscape":"f225"},
         {"icon":"venus","unicodeEscape":"f221"},
         {"icon":"venus-double","unicodeEscape":"f226"},
         {"icon":"venus-mars","unicodeEscape":"f228"},
         /* Archivo */
         {"icon":"file","unicodeEscape":"f15b"},
         {"icon":"file-archive-o","unicodeEscape":"f1c6"},
         {"icon":"file-audio-o","unicodeEscape":"f1c7"},
         {"icon":"file-code-o","unicodeEscape":"f1c9"},
         {"icon":"file-excel-o","unicodeEscape":"f1c3"},
         {"icon":"file-image-o","unicodeEscape":"f1c5"},
         {"icon":"file-movie-o","unicodeEscape":"f1c8"},
         {"icon":"file-o","unicodeEscape":"f016"},
         {"icon":"file-pdf-o","unicodeEscape":"f1c1"},
         {"icon":"file-photo-o","unicodeEscape":"f1c5"},
         {"icon":"file-picture-o","unicodeEscape":"f1c5"},
         {"icon":"file-powerpoint-o","unicodeEscape":"f1c4"},
         {"icon":"file-sound-o","unicodeEscape":"f1c7"},
         {"icon":"file-text","unicodeEscape":"f15c"},
         {"icon":"file-text-o","unicodeEscape":"f0f6"},
         {"icon":"file-video-o","unicodeEscape":"f1c8"},
         {"icon":"file-word-o","unicodeEscape":"f1c2"},
         {"icon":"file-zip-o","unicodeEscape":"f1c6"},
         /* Giro */
         {"icon":"circle-o-notch","unicodeEscape":"f1ce"},
         {"icon":"cog","unicodeEscape":"f013"},
         {"icon":"gear","unicodeEscape":"f013"},
         {"icon":"refresh","unicodeEscape":"f021"},
         {"icon":"spinner","unicodeEscape":"f110"},
         /* Formulario */
         {"icon":"check-square","unicodeEscape":"f14a"},
         {"icon":"check-square-o","unicodeEscape":"f046"},
         {"icon":"circle","unicodeEscape":"f111"},
         {"icon":"circle-o","unicodeEscape":"f10c"},
         {"icon":"dot-circle-o","unicodeEscape":"f192"},
         {"icon":"minus-square","unicodeEscape":"f146"},
         {"icon":"minus-square-o","unicodeEscape":"f147"},
         {"icon":"plus-square","unicodeEscape":"f0fe"},
         {"icon":"plus-square-o","unicodeEscape":"f196"},
         {"icon":"square","unicodeEscape":"f0c8"},
         {"icon":"square-o","unicodeEscape":"f096"},
         /* Pago */
         {"icon":"cc-amex","unicodeEscape":"f1f3"},
         {"icon":"cc-diners-club","unicodeEscape":"f24c"},
         {"icon":"cc-discover","unicodeEscape":"f1f2"},
         {"icon":"cc-jcb","unicodeEscape":"f24b"},
         {"icon":"cc-mastercard","unicodeEscape":"f1f1"},
         {"icon":"cc-paypal","unicodeEscape":"f1f4"},
         {"icon":"cc-stripe","unicodeEscape":"f1f5"},
         {"icon":"cc-visa","unicodeEscape":"f1f0"},
         {"icon":"credit-card","unicodeEscape":"f09d"},
         {"icon":"credit-card-alt","unicodeEscape":"f283"},
         {"icon":"google-wallet","unicodeEscape":"f1ee"},
         {"icon":"paypal","unicodeEscape":"f1ed"},
         /* Gráficos */ 
         {"icon":"area-chart","unicodeEscape":"f1fe"},
         {"icon":"bar-chart","unicodeEscape":"f080"},
         {"icon":"bar-chart-o","unicodeEscape":"f080"},
         {"icon":"line-chart","unicodeEscape":"f201"},
         {"icon":"pie-chart","unicodeEscape":"f200"},
         /* Moneda */ 
         {"icon":"bitcoin","unicodeEscape":"f15a"},
         {"icon":"btc","unicodeEscape":"f15a"},
         {"icon":"cny","unicodeEscape":"f157"},
         {"icon":"dollar","unicodeEscape":"f155"},
         {"icon":"eur","unicodeEscape":"f153"},
         {"icon":"euro","unicodeEscape":"f153"},
         {"icon":"gbp","unicodeEscape":"f154"},
         {"icon":"gg","unicodeEscape":"f260"},
         {"icon":"gg-circle","unicodeEscape":"f261"},
         {"icon":"ils","unicodeEscape":"f20b"},
         {"icon":"inr","unicodeEscape":"f156"},
         {"icon":"jpy","unicodeEscape":"f157"},
         {"icon":"krw","unicodeEscape":"f159"},
         {"icon":"money","unicodeEscape":"f0d6"},
         {"icon":"rmb","unicodeEscape":"f157"},
         {"icon":"rouble","unicodeEscape":"f158"},
         {"icon":"rub","unicodeEscape":"f158"},
         {"icon":"ruble","unicodeEscape":"f158"},
         {"icon":"rupee","unicodeEscape":"f156"},
         {"icon":"shekel","unicodeEscape":"f20b"},
         {"icon":"sheqel","unicodeEscape":"f20b"},
         {"icon":"try","unicodeEscape":"f195"},
         {"icon":"turkish-lira","unicodeEscape":"f195"},
         {"icon":"usd","unicodeEscape":"f155"},
         {"icon":"won","unicodeEscape":"f159"},
         {"icon":"yen","unicodeEscape":"f157"},
         /* Edición de texto */ 
         {"icon":"align-center","unicodeEscape":"f037"},
         {"icon":"align-justify","unicodeEscape":"f039"},
         {"icon":"align-left","unicodeEscape":"f036"},
         {"icon":"align-right","unicodeEscape":"f038"},
         {"icon":"bold","unicodeEscape":"f032"},
         {"icon":"chain","unicodeEscape":"f0c1"},
         {"icon":"chain-broken","unicodeEscape":"f127"},
         {"icon":"clipboard","unicodeEscape":"f0ea"},
         {"icon":"columns","unicodeEscape":"f0db"},
         {"icon":"copy","unicodeEscape":"f0c5"},
         {"icon":"cut","unicodeEscape":"f0c4"},
         {"icon":"dedent","unicodeEscape":"f03b"},
         {"icon":"eraser","unicodeEscape":"f12d"},
         {"icon":"file", "unicodeEscape":"f15b"},
         {"icon":"file-o","unicodeEscape":"f016"},
         {"icon":"file-text","unicodeEscape":"f15c"},
         {"icon":"file-text-o","unicodeEscape":"f0f6"},
         {"icon":"files-o","unicodeEscape":"f0c5"},
         {"icon":"floppy-o","unicodeEscape":"f0c7"},
         {"icon":"font","unicodeEscape":"f031"},
         {"icon":"header","unicodeEscape":"f1dc"},
         {"icon":"indent","unicodeEscape":"f03c"},
         {"icon":"italic","unicodeEscape":"f033"},
         {"icon":"link","unicodeEscape":"f0c1"},
         {"icon":"list","unicodeEscape":"f03a"},
         {"icon":"list-alt","unicodeEscape":"f022"},
         {"icon":"list-ol","unicodeEscape":"f0cb"},
         {"icon":"list-ul","unicodeEscape":"f0ca"},
         {"icon":"outdent","unicodeEscape":"f03b"},
         {"icon":"paperclip","unicodeEscape":"f0c6"},
         {"icon":"paragraph","unicodeEscape":"f1dd"},
         {"icon":"paste","unicodeEscape":"f0ea"},
         {"icon":"repeat","unicodeEscape":"f01e"},
         {"icon":"rotate-left","unicodeEscape":"f0e2"},
         {"icon":"rotate-right","unicodeEscape":"f01e"},
         {"icon":"save","unicodeEscape":"f0c7"},
         {"icon":"scissors","unicodeEscape":"f0c4"},
         {"icon":"strikethrough","unicodeEscape":"f0cc"},
         {"icon":"subscript","unicodeEscape":"f12c"},
         {"icon":"superscript","unicodeEscape":"f12b"},
         {"icon":"table","unicodeEscape":"f0ce"},
         {"icon":"text-height","unicodeEscape":"f034"},
         {"icon":"text-width","unicodeEscape":"f035"},
         {"icon":"th","unicodeEscape":"f00a"},
         {"icon":"th-large","unicodeEscape":"f009"},
         {"icon":"th-list","unicodeEscape":"f00b"},
         {"icon":"underline","unicodeEscape":"f0cd"},
         {"icon":"undo","unicodeEscape":"f0e2"},
         {"icon":"unlink","unicodeEscape":"f127"},
         /* Íconos direccionales */ 
         {"icon":"angle-double-down","unicodeEscape":"f103"},
         {"icon":"angle-double-left","unicodeEscape":"f100"},
         {"icon":"angle-double-right","unicodeEscape":"f101"},
         {"icon":"angle-double-up","unicodeEscape":"f102"},
         {"icon":"angle-down","unicodeEscape":"f107"},
         {"icon":"angle-left","unicodeEscape":"f104"},
         {"icon":"angle-right","unicodeEscape":"f105"},
         {"icon":"angle-up","unicodeEscape":"f106"},
         {"icon":"arrow-circle-down","unicodeEscape":"f0ab"},
         {"icon":"arrow-circle-left","unicodeEscape":"f0a8"},
         {"icon":"arrow-circle-o-down","unicodeEscape":"f01a"},
         {"icon":"arrow-circle-o-left","unicodeEscape":"f190"},
         {"icon":"arrow-circle-o-right","unicodeEscape":"f18e"},
         {"icon":"arrow-circle-o-up","unicodeEscape":"f01b"},
         {"icon":"arrow-circle-right","unicodeEscape":"f0a9"},
         {"icon":"arrow-circle-up","unicodeEscape":"f0aa"},
         {"icon":"arrow-down","unicodeEscape":"f063"},
         {"icon":"arrow-left","unicodeEscape":"f060"},
         {"icon":"arrow-right","unicodeEscape":"f061"},
         {"icon":"arrow-up","unicodeEscape":"f062"},
         {"icon":"arrows","unicodeEscape":"f047"},
         {"icon":"arrows-alt","unicodeEscape":"f0b2"},
         {"icon":"arrows-h","unicodeEscape":"f07e"},
         {"icon":"arrows-v","unicodeEscape":"f07d"},
         {"icon":"caret-down","unicodeEscape":"f0d7"},
         {"icon":"caret-left","unicodeEscape":"f0d9"},
         {"icon":"caret-right","unicodeEscape":"f0da"},
         {"icon":"caret-square-o-down","unicodeEscape":"f150"},
         {"icon":"caret-square-o-left","unicodeEscape":"f191"},
         {"icon":"caret-square-o-right","unicodeEscape":"f152"},
         {"icon":"caret-square-o-up", "unicodeEscape":"f151"},
         {"icon":"caret-up","unicodeEscape":"f0d8"},
         {"icon":"chevron-circle-down","unicodeEscape":"f13a"},
         {"icon":"chevron-circle-left","unicodeEscape":"f137"},
         {"icon":"chevron-circle-right","unicodeEscape":"f138"},
         {"icon":"chevron-circle-up","unicodeEscape":"f139"},
         {"icon":"chevron-down", "unicodeEscape":"f078"},
         {"icon":"chevron-left","unicodeEscape":"f053"},
         {"icon":"chevron-right","unicodeEscape":"f054"},
         {"icon":"chevron-up","unicodeEscape":"f077"},
         {"icon":"exchange","unicodeEscape":"f0ec"},
         {"icon":"hand-o-down","unicodeEscape":"f0a7"},
         {"icon":"hand-o-left","unicodeEscape":"f0a5"},
         {"icon":"hand-o-right","unicodeEscape":"f0a4"},
         {"icon":"hand-o-up","unicodeEscape":"f0a6"},
         {"icon":"long-arrow-down","unicodeEscape":"f175"},
         {"icon":"long-arrow-left","unicodeEscape":"f177"},
         {"icon":"long-arrow-right","unicodeEscape":"f178"},
         {"icon":"long-arrow-up","unicodeEscape":"f176"},
         {"icon":"toggle-down","unicodeEscape":"f150"},
         {"icon":"toggle-left","unicodeEscape":"f191"},
         {"icon":"toggle-right","unicodeEscape":"f152"},
         {"icon":"toggle-up","unicodeEscape":"f151"},
         /* Reproducción de video */ 
         {"icon":"arrows-alt","unicodeEscape":"f0b2"},
         {"icon":"backward","unicodeEscape":"f04a"},
         {"icon":"compress","unicodeEscape":"f066"},
         {"icon":"eject","unicodeEscape":"f052"},
         {"icon":"expand","unicodeEscape":"f065"},
         {"icon":"fast-backward","unicodeEscape":"f049"},
         {"icon":"fast-forward","unicodeEscape":"f050"},
         {"icon":"forward","unicodeEscape":"f04e"},
         {"icon":"pause","unicodeEscape":"f04c"},
         {"icon":"pause-circle","unicodeEscape":"f28b"},
         {"icon":"play","unicodeEscape":"f04b"},
         {"icon":"play-circle","unicodeEscape":"f144"},
         {"icon":"play-circle-o","unicodeEscape":"f01d"},
         {"icon":"random","unicodeEscape":"f074"},
         {"icon":"step-backward","unicodeEscape":"f048"},
         {"icon":"step-forward","unicodeEscape":"f051"},
         {"icon":"stop","unicodeEscape":"f04d"},
         {"icon":"stop-circle","unicodeEscape":"f28d"},
         {"icon":"stop-circle-o","unicodeEscape":"f28e"},
         {"icon":"youtube-play","unicodeEscape":"f16a"}
    ]
};
            
document.getElementById("hexFaSearchText").addEventListener("input", function(){    
    searchStrByHexFaInput = document.getElementById("hexFaSearchText").value;
    for(i in escapeIndex.fontAwesomeIcons) {
        // console.log(escapeIndex.fontAwesomeIcons[i]);
        if (searchStrByHexFaInput == escapeIndex.fontAwesomeIcons[i].unicodeEscape.slice(1,4)) {
            iconFound = escapeIndex.fontAwesomeIcons[i].icon;
            hexFaIcon.classList = "";
            hexFaIcon.classList.add("fa");
            hexFaIcon.classList.add("fa-fw");
            hexFaIcon.classList.add("fa-" + escapeIndex.fontAwesomeIcons[i].icon);
            document.getElementById("hexFaIconName").innerHTML = iconFound; 
        }
    }
});
            
document.getElementById("faHexSearchText").addEventListener("input", function(){
    searchStrByFaHexInput = document.getElementById("faHexSearchText").value; 
    for(j in escapeIndex.fontAwesomeIcons) {
        // console.log(escapeIndex.fontAwesomeIcons[j]);
        if(searchStrByFaHexInput == escapeIndex.fontAwesomeIcons[j].icon) {
            hexFound = escapeIndex.fontAwesomeIcons[j].unicodeEscape.slice(1,4);
            faHexIcon.classList = "";
            faHexIcon.classList.add("fa");
            faHexIcon.classList.add("fa-fw");
            faHexIcon.classList.add("fa-" + escapeIndex.fontAwesomeIcons[j].icon);
            document.getElementById("faHexCode").innerHTML = "&#092;uf" + hexFound; 
        }
    }
});
            